[package]
name = "lib"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
bootstrap = ["dep:bootstrap"]
bootstrap-openapi = ["bootstrap", "bootstrap/openapi"]

domain = ["dep:domain"]

infrastructure = ["dep:infrastructure"]

infrastructure-instrumentation = [
  "infrastructure",
  "infrastructure/instrumentation",
]

infrastructure-instrumentation-opentelemetry-http-proto = [
  "infrastructure-instrumentation",
  "infrastructure/instrumentation-opentelemetry-http-proto",
]

infrastructure-instrumentation-opentelemetry-http-json = [
  "infrastructure-instrumentation",
  "infrastructure/instrumentation-opentelemetry-http-json",
]

infrastructure-instrumentation-opentelemetry-grpc-tonic = [
  "infrastructure-instrumentation",
  "infrastructure/instrumentation-opentelemetry-grpc-tonic",
]

infrastructure-persistence = ["infrastructure/persistence"]
infrastructure-persistence-postgres = [
  "infrastructure/persistence",
  "infrastructure/persistence-postgres",
]

macros = ["dep:macros"]
macros-proc = ["macros", "macros/proc"]

presentation = ["dep:presentation"]

presentation-api = ["presentation", "presentation/api"]
presentation-api-rest = ["presentation/api", "presentation/api-rest"]

presentation-bot = ["presentation/bot"]
presentation-bot-telegram = ["presentation/bot", "presentation/bot-telegram"]

[dependencies]
bootstrap = { path = "./bootstrap", package = "lib-bootstrap", optional = true }
infrastructure = { path = "./infrastructure", package = "lib-infrastructure", optional = true }
domain = { path = "./domain", package = "lib-domain", optional = true }
macros = { path = "./macros", package = "lib-macros", optional = true }
presentation = { path = "./presentation", package = "lib-presentation", optional = true }

[lints]
workspace = true
