[package]
name = "ad_platform-presentation-api-rest"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
lib = { workspace = true, features = ["presentation_api_rest"] }
kernel = { path = "../../../kernel", package = "ad_platform-kernel" }

axum = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tracing.workspace = true
utoipa = { workspace = true, features = [
    "axum_extras",
    "preserve_order",
    "preserve_path_order",
    "non_strict_integers",
    "uuid",
    "chrono",
] }
utoipa-axum.workspace = true
uuid = { workspace = true, features = ["serde"] }

[lints]
workspace = true
