[package]
name = "infrastructure-service-hasher"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../../../kernel"}

thiserror.workspace = true
tracing.workspace = true

argon2 = "0.5"

[lints]
workspace = true
