[package]
name = "kernel"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
# tracing.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["v7"] }

[lints]
workspace = true
