[package]
name = "ad_platform-infrastructure-services-hasher-argon2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
application = { path = "../../../../application", package = "ad_platform-application" }

thiserror.workspace = true
tracing.workspace = true

argon2 = "0.5"

[lints]
workspace = true
