[package]
name = "ad_platform-infrastructure-services-hasher-argon2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../../../kernel", package = "ad_platform-kernel" }

thiserror.workspace = true
tracing.workspace = true

argon2 = "0.5"

[lints]
workspace = true
