[package]
name = "lib-infrastructure-instrumentation-opentelemetry"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
http-proto = ["opentelemetry-otlp/http-proto"]
http-json = ["opentelemetry-otlp/http-json"]
grpc-tonic = ["opentelemetry-otlp/grpc-tonic"]

[dependencies]
metrics.workspace = true
tokio.workspace = true
tracing.workspace = true

metrics-exporter-prometheus = "0.17"
metrics-process = "2.4"
metrics-tracing-context = "0.18"
metrics-util = "0.20"
opentelemetry = { version = "0.30", features = ["trace", "logs", "metrics"] }
opentelemetry_sdk = { version = "0.30", features = [
  "rt-tokio",
  "trace",
  "logs",
  "metrics",
] }
opentelemetry-appender-tracing = { version = "0.30", features = [
  "experimental_metadata_attributes",
  #    "spec_unstable_logs_enabled",
  "experimental_use_tracing_span_context",
] }
opentelemetry-otlp = { version = "0.30", default-features = false, features = [
  "trace",
  "logs",
  "metrics",
] }
opentelemetry-semantic-conventions = { version = "0.30", features = [
  "semconv_experimental",
] }
tokio-metrics = { version = "0.4", features = ["rt", "metrics-rs-integration"] }
tracing-opentelemetry = "0.31"
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "env-filter",
  "json",
  "registry",
  "std",
] }

[lints]
workspace = true
