[package]
name = "ad_platform-infrastructure-services-token-jwt"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../../../kernel", package = "ad_platform-kernel" }

chrono.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true

jsonwebtoken = "9.3"

[lints]
workspace = true
