[package]
name = "lib-infrastructure-instrumentation"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
opentelemetry-http-proto = ["dep:opentelemetry", "opentelemetry/http-proto"]
opentelemetry-http-json = ["dep:opentelemetry", "opentelemetry/http-json"]
opentelemetry-grpc-tonic = ["dep:opentelemetry", "opentelemetry/grpc-tonic"]

[dependencies]
opentelemetry = { path = "./opentelemetry", package = "lib-infrastructure-instrumentation-opentelemetry", optional = true }


[lints]
workspace = true
